import type { Metadata } from "next";
import "@/styles/globals.css";
import { JetBrains_Mono as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import AuthProvider from "@/Provider";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
        }}
      >
        <AuthProvider>
          <div className="m-10">{children}</div>

          <div className="fixed bottom-0 w-full">
            <Navbar />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
